// host/seed/music.json -> firmware/main/music.inc
//
//   cd host && node scripts/gen-music.mjs
//
// Same shape as gen-cries.mjs: the seed is the single source, the .inc is
// generated, and nothing in firmware/ is edited by hand. What is different is
// that the seed here is written in note NAMES rather than Hz, because a tune is
// something you tweak by ear and "A#5/8" is editable in a way that "932.33f" is
// not. `resolveScore` below does the conversion and is exported so
// cries-to-wav.mjs can audition exactly what the device will play.
//
// The extra sound ids live ABOVE the 156 species cries (SND_EXTRA_BASE =
// SND_SPECIES_BASE + SND_SPECIES_COUNT) rather than next to BUI/EVOLVE/HOUR.
// Inserting them at the bottom would shift every species id by three, and a
// species id is `soundBase + index` on the host -- every cry would come out as
// the wrong pokemon until the firmware was reflashed in lockstep.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const fnum = (v) => (Number.isInteger(v) ? `${v}.f` : `${v}f`);

// A4 = 440, equal temperament. Returns 0 for a rest, which is what synth_tone
// reads as "silent gap".
const SEMITONE = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 };

export function noteHz(name) {
  if (name === "-") return 0;
  const m = /^([A-G])([#b]?)(-?\d)$/.exec(name);
  if (!m) throw new Error(`bad note name: ${name}`);
  const [, letter, accidental, octave] = m;
  const semis = SEMITONE[letter] + (accidental === "#" ? 1 : accidental === "b" ? -1 : 0);
  const midi = (Number(octave) + 1) * 12 + semis;
  return Math.round(440 * 2 ** ((midi - 69) / 12) * 100) / 100;
}

// "D5/8" = an eighth note at the score's tempo; "F6:700" = 700ms flat. Both
// forms exist because the loop is metrical and the fanfare is not -- a jingle
// gets its shape from a held last note, not from the grid.
export function noteMs(token, wholeMs) {
  const [, denom] = /\/(\d+)$/.exec(token) ?? [];
  if (denom) return Math.round(wholeMs / Number(denom));
  const [, ms] = /:(\d+)$/.exec(token) ?? [];
  if (ms) return Number(ms);
  throw new Error(`bad duration: ${token}`);
}

export function resolveNote(token, wholeMs) {
  const name = token.split(/[/:]/)[0];
  const hz = noteHz(name);
  // f0 === f1: the music is fixed-pitch. The sweep fields exist for the cries,
  // where a note bending is the whole character of the voice.
  return { f0: hz, f1: hz, ms: noteMs(token, wholeMs) };
}

// Turns the seed into the same {f0,f1,ms} note objects the cry seed stores
// literally, so every downstream consumer sees one note format.
export function resolveScore(data) {
  const wholeMs = Math.round((60000 / data.tempoBpm) * 4);
  return data.extra.map((track, index) => {
    const common = { key: track.key, cname: track.cname, kind: track.kind, title: track.title, index };
    if (track.kind === "loop") {
      return { ...common, phrases: track.phrases.map((p) => p.map((t) => resolveNote(t, wholeMs))) };
    }
    if (track.kind === "oneshot") {
      return { ...common, notes: track.notes.map((t) => resolveNote(t, wholeMs)) };
    }
    return common;   // control ids carry no audio at all
  });
}

export function loadScore() {
  return resolveScore(JSON.parse(
    readFileSync(fileURLToPath(new URL("../seed/music.json", import.meta.url)), "utf8")));
}

export function generateInc(data) {
  const tracks = resolveScore(data);
  const noteList = (notes) => notes.map((n) => `{${fnum(n.f0)}, ${fnum(n.f1)}, ${n.ms}}`).join(", ");

  const lines = [
    "// AUTO-GENERATED by host/scripts/gen-music.mjs from host/seed/music.json",
    "// Do not edit by hand. Regenerate: cd host && node scripts/gen-music.mjs",
    "//",
    "// Ids are offsets from SND_EXTRA_BASE, which main.cpp sets to",
    "// SND_SPECIES_BASE + SND_SPECIES_COUNT so the species table never moves.",
    `#define SND_EXTRA_COUNT ${tracks.length}`,
  ];
  // ASCII keys, not the Chinese titles: this file is #included into a translation
  // unit and there is no reason to make the build depend on comment encoding.
  for (const t of tracks) lines.push(`#define SND_EXTRA_${t.cname} ${t.index}   // ${t.key} (${t.kind})`);
  lines.push("", "struct Phrase { const Note *notes; int count; };", "");

  for (const t of tracks) {
    if (t.kind === "loop") {
      t.phrases.forEach((p, i) => {
        lines.push(`static const Note ${t.cname}_P${i}[] = { ${noteList(p)} };`);
      });
      lines.push(`static const Phrase ${t.cname}_PHRASES[] = {`);
      t.phrases.forEach((p, i) => lines.push(`  { ${t.cname}_P${i}, ${p.length} },`));
      lines.push("};",
        `static constexpr int ${t.cname}_PHRASE_COUNT = ${t.phrases.length};`, "");
    } else if (t.kind === "oneshot") {
      lines.push(`static const Note ${t.cname}_NOTES[] = { ${noteList(t.notes)} };`,
        `static constexpr int ${t.cname}_NOTE_COUNT = ${t.notes.length};`, "");
    }
  }
  return lines.join("\n");
}

const isCli = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isCli) {
  const data = JSON.parse(
    readFileSync(fileURLToPath(new URL("../seed/music.json", import.meta.url)), "utf8"));
  const out = fileURLToPath(new URL("../../firmware/main/music.inc", import.meta.url));
  writeFileSync(out, generateInc(data));
  console.log(`wrote ${out}`);
}
